### ISSUE TITLE
cmdwrap build

### ISSUE THREAD

**Issue by kueken** [e2iplayer/e2ibox#1]
Hello samsamsam,

could you give me a tip on how to compile the cmdwrap so that the output and version in the e2iplayer fits?
```
do_compile() {
    ${CC} ${SOURCE_FILES} -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -o cmdwrap ${LDFLAGS}
}
```

**Comment by e2iplayer** [comment]
This utility is something like "busybox" it aggregate three previously used by E2iPlayer tools:
- cmdwrapper
- lsdir
- nice

e2ibox with these three applets was added for the E2iPlayer private version.
It is not dedicated to be used in the old public version. It is probably possible but there is need to change source code a little bit.

There is need to add:
> Version: 2

to

> cmdwrapper_main

Something like that:
> printf("Version: 2\n");
> printf("%s input_file args_splitter [priority]\n", argv[0]);

**Comment by e2iplayer** [comment]
Please try
https://github.com/e2iplayer/e2ibox/commit/79d455ef3162086faa9498f3aefa40362942205b

**Comment by kueken** [comment]
Many Thanks
